server:
  port: 8011

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5          # 租约续期时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 2       # 租约持续时间（默认90秒）
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true         # 开启健康检查（需要spring-boot-starter-actuator依赖

spring:
  application:
    name: employee-service

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG